version: '3.7'
volumes:
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE:-challenge}
      POSTGRES_USER: ${DB_USERNAME:-challenge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Please set password for database user 'challenge'}
    ports:
      - 5432:5432


